import React from 'react';
import { motion } from 'framer-motion';
import { Shield, Lock, Eye, FileText, Server, UserCheck } from 'lucide-react';

const PrivacyPolicy: React.FC = () => {
  const lastUpdated = "August 14, 2025";
  
  return (
    <div className="min-h-screen pt-24 pb-16 px-4 sm:px-6 lg:px-8 max-w-7xl mx-auto">
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5 }}
        className="bg-gray-900/50 backdrop-blur-sm rounded-2xl p-8 border border-purple-500/20 shadow-xl"
      >
        <div className="text-center mb-12">
          <h1 className="text-4xl md:text-5xl font-bold bg-gradient-to-r from-cyan-400 to-purple-400 bg-clip-text text-transparent mb-4">
            CloudSphereX
          </h1>
          <p className="text-xl text-gray-300 mb-2">Privacy Policy</p>
          <p className="text-sm text-gray-400">Last updated: {lastUpdated}</p>
        </div>

        <div className="space-y-10 text-gray-300">
          <section>
            <div className="flex items-center mb-4">
              <Shield className="w-6 h-6 text-cyan-400 mr-3" />
              <h2 className="text-2xl font-semibold text-white">Introduction</h2>
            </div>
            <p className="mb-4">
              CloudSphereX ("we," "our," or "us") is committed to protecting your privacy. This Privacy Policy explains how your personal information is collected, used, and disclosed by CloudSphereX.
            </p>
            <p>
              This Privacy Policy applies to our website, and its associated subdomains (collectively, our "Service"). By accessing or using our Service, you signify that you have read, understood, and agree to our collection, storage, use, and disclosure of your personal information as described in this Privacy Policy.
            </p>
          </section>

          <section>
            <div className="flex items-center mb-4">
              <FileText className="w-6 h-6 text-cyan-400 mr-3" />
              <h2 className="text-2xl font-semibold text-white">Definitions and Key Terms</h2>
            </div>
            <p className="mb-4">
              For this Privacy Policy:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li><strong>Cookie:</strong> A small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, and remember information about you such as your language preference or login information.</li>
              <li><strong>Company:</strong> When this policy mentions "Company," "we," "us," or "our," it refers to CloudSphereX that is responsible for your information under this Privacy Policy.</li>
              <li><strong>Personal Data:</strong> Any information that directly, indirectly, or in connection with other information allows for the identification of a natural person.</li>
              <li><strong>Service:</strong> Refers to the website and any applications, software, or services offered by CloudSphereX.</li>
              <li><strong>Third-party service:</strong> Refers to advertisers, sponsors, partners, and other third parties that provide data, services, or products to CloudSphereX.</li>
              <li><strong>Website:</strong> CloudSphereX's site, which can be accessed via this URL: www.cloudsphereX.com</li>
              <li><strong>You:</strong> A person or entity that is registered with CloudSphereX to use the Services.</li>
            </ul>
          </section>

          <section>
            <div className="flex items-center mb-4">
              <Eye className="w-6 h-6 text-cyan-400 mr-3" />
              <h2 className="text-2xl font-semibold text-white">Information We Collect</h2>
            </div>
            <p className="mb-4">
              We collect information from you when you visit our website, register on our site, place an order, subscribe to our newsletter, respond to a survey, fill out a form, or otherwise contact us.
            </p>
            <div className="bg-white/5 backdrop-blur-sm rounded-xl p-6 border border-purple-500/20">
              <h3 className="text-xl font-semibold text-cyan-400 mb-3">We may collect the following types of information:</h3>
              <ul className="list-disc pl-6 space-y-2">
                <li><strong>Personal Information:</strong> Name, email address, phone number, billing address, and other similar contact data.</li>
                <li><strong>Credentials:</strong> Passwords and similar security information used for authentication and account access.</li>
                <li><strong>Payment Data:</strong> Data necessary to process your payment if you make purchases, such as your payment instrument number (such as a credit card number).</li>
                <li><strong>Usage Data:</strong> Information about how you use our website and services, including which pages you visit, how long you stay, and other similar data.</li>
                <li><strong>Device Information:</strong> Information about the device you use to access our website, including hardware model, operating system, and browser type.</li>
              </ul>
            </div>
          </section>

          <section>
            <div className="flex items-center mb-4">
              <Server className="w-6 h-6 text-cyan-400 mr-3" />
              <h2 className="text-2xl font-semibold text-white">How We Use Your Information</h2>
            </div>
            <p className="mb-4">
              We use the information we collect in various ways, including to:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Provide, operate, and maintain our website and services</li>
              <li>Improve, personalize, and expand our website and services</li>
              <li>Understand and analyze how you use our website and services</li>
              <li>Develop new products, services, features, and functionality</li>
              <li>Communicate with you, either directly or through one of our partners, for customer service, updates and other information relating to the website</li>
              <li>Send you emails and newsletters</li>
              <li>Process your transactions</li>
              <li>Find and prevent fraud</li>
            </ul>
          </section>

          <section>
            <div className="flex items-center mb-4">
              <Lock className="w-6 h-6 text-cyan-400 mr-3" />
              <h2 className="text-2xl font-semibold text-white">Security of Your Personal Information</h2>
            </div>
            <p className="mb-4">
              We take steps to ensure that your information is treated securely and in accordance with this Privacy Policy. Unfortunately, no internet transmission is ever completely secure. While we strive to protect your personal information, we cannot guarantee the security of information transmitted to our website. Any transmission is at your own risk.
            </p>
            <p>
              We have implemented appropriate technical and organizational security measures designed to protect the security of any personal information we process. However, despite our safeguards and efforts to secure your information, no electronic transmission over the Internet or information storage technology can be guaranteed to be 100% secure.
            </p>
          </section>

          <section>
            <div className="flex items-center mb-4">
              <UserCheck className="w-6 h-6 text-cyan-400 mr-3" />
              <h2 className="text-2xl font-semibold text-white">Your Rights</h2>
            </div>
            <p className="mb-4">
              You have certain rights regarding your personal information. These include:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li><strong>The right to access</strong> - You have the right to request copies of your personal data.</li>
              <li><strong>The right to rectification</strong> - You have the right to request that we correct any information you believe is inaccurate or complete information you believe is incomplete.</li>
              <li><strong>The right to erasure</strong> - You have the right to request that we erase your personal data, under certain conditions.</li>
              <li><strong>The right to restrict processing</strong> - You have the right to request that we restrict the processing of your personal data, under certain conditions.</li>
              <li><strong>The right to object to processing</strong> - You have the right to object to our processing of your personal data, under certain conditions.</li>
              <li><strong>The right to data portability</strong> - You have the right to request that we transfer the data that we have collected to another organization, or directly to you, under certain conditions.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">Changes to This Privacy Policy</h2>
            <p className="mb-4">
              We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page and updating the "Last Updated" date.
            </p>
            <p>
              You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">Contact Us</h2>
            <p className="mb-4">
              If you have any questions about this Privacy Policy, please contact us:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>By email: info@cloudsphereX.com</li>
              <li>By phone: 051-2305230</li>
              <li>By visiting this page on our website: www.cloudsphereX.com/contact</li>
            </ul>
          </section>
        </div>
      </motion.div>
    </div>
  );
};

export default PrivacyPolicy;